services:
  nextjs:
    container_name: workout-app
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
  prismaliser:
    container_name: prismaliser
    build:
      dockerfile: ./prismaliser/Dockerfile.dev
    ports:
      - "8080:8080"
