name: Jest Tests
on: [push]
#   pull_request:
#     branches: -master
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node_modules
        run: yarn install && yarn prisma generate
      - name: Run Jest Tests
        run: yarn jest-ci
