name: Typescript Eslint Recommended
# on:
#   pull_request:
#     branches:
#       - master
on: [push]
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node_modules
        run: yarn install
      - name: Run ESLint
        run: yarn lint
